/*
 *  Andre Cavalcante e Rafael Mendonca
 *  Copyright UFAM 2015-2016
 */
package test.siape;

import eps.Util;
import jade.core.ProfileImpl;
import jade.gui.GuiEvent;
import jade.wrapper.AgentController;
import jade.wrapper.ContainerController;
import jade.wrapper.StaleProxyException;
import java.io.PrintStream;
import javax.swing.DefaultListModel;

/**
 *
 * @author Rafael
 */
public class OrderGui extends javax.swing.JFrame {

    private OrderAgent oa;

    /**
     * Creates new form OrderGui
     */
    public OrderGui(String host) {
        initComponents();
        initOrderAgent(host);
        
        Util.JTextAreaOutputStream os = new Util.JTextAreaOutputStream(jTextArea1);
        PrintStream ps = new PrintStream(os);
        System.setOut(ps);
        System.setErr(ps);

        anagramList.setModel(new DefaultListModel());
        orderList.setModel(new DefaultListModel());
        failureList.setModel(new DefaultListModel());
        producedList.setModel(new DefaultListModel());
    }

    private void initOrderAgent(String host) {
        jade.core.Runtime rt = jade.core.Runtime.instance();
        ContainerController cc = rt.createAgentContainer(new ProfileImpl(host, 1099, null, false));
        oa = new OrderAgent(this);
        try {
            AgentController ac = cc.acceptNewAgent("order", oa);
            ac.start();
        } catch (StaleProxyException ex) {
            System.out.println("Not start OrderAngent. Exception: " + ex);
            System.exit(-1);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        AvailablesTxt = new javax.swing.JTextField();
        jPanel18 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        anagramList = new javax.swing.JList();
        jPanel12 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jSpinner1 = new javax.swing.JSpinner();
        jPanel9 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        orderList = new javax.swing.JList();
        jPanel16 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        producedList = new javax.swing.JList();
        jPanel15 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        failureList = new javax.swing.JList();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("EPS - Production Order");
        setMinimumSize(new java.awt.Dimension(380, 200));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setLayout(new java.awt.GridLayout(1, 5, 10, 0));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(" Anagrams"));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder(" Availables  "));
        jPanel13.setLayout(new java.awt.BorderLayout());

        AvailablesTxt.setEditable(false);
        AvailablesTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AvailablesTxtActionPerformed(evt);
            }
        });
        jPanel13.add(AvailablesTxt, java.awt.BorderLayout.CENTER);

        jPanel18.setPreferredSize(new java.awt.Dimension(178, 32));
        jPanel18.setLayout(new java.awt.BorderLayout());

        jLabel4.setPreferredSize(new java.awt.Dimension(30, 20));
        jPanel18.add(jLabel4, java.awt.BorderLayout.WEST);

        jButton8.setText("Refresh");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel18.add(jButton8, java.awt.BorderLayout.CENTER);

        jLabel5.setPreferredSize(new java.awt.Dimension(30, 20));
        jPanel18.add(jLabel5, java.awt.BorderLayout.EAST);

        jPanel13.add(jPanel18, java.awt.BorderLayout.SOUTH);

        jPanel3.add(jPanel13, java.awt.BorderLayout.PAGE_START);

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(" Anagrams "));

        jScrollPane2.setViewportView(anagramList);

        jPanel3.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel12.setPreferredSize(new java.awt.Dimension(178, 32));
        jPanel12.setLayout(new java.awt.GridLayout(1, 0));

        jButton4.setText("Add");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel12.add(jButton4);

        jButton5.setText("Remove");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel12.add(jButton5);

        jPanel3.add(jPanel12, java.awt.BorderLayout.SOUTH);

        jPanel1.add(jPanel3);
        jPanel3.getAccessibleContext().setAccessibleName(" Products");

        jPanel7.setLayout(new java.awt.BorderLayout());

        jPanel14.setPreferredSize(new java.awt.Dimension(190, 40));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 192, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel7.add(jPanel14, java.awt.BorderLayout.NORTH);

        jPanel8.setPreferredSize(new java.awt.Dimension(15, 10));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 286, Short.MAX_VALUE)
        );

        jPanel7.add(jPanel8, java.awt.BorderLayout.WEST);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Count");

        jButton1.setText("Add to Order");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Remove from Order");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Clear all orders");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(1, 1, 20, 1));
        jSpinner1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        jPanel7.add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel9.setPreferredSize(new java.awt.Dimension(15, 10));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 286, Short.MAX_VALUE)
        );

        jPanel7.add(jPanel9, java.awt.BorderLayout.EAST);

        jPanel17.setPreferredSize(new java.awt.Dimension(190, 40));

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 192, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel7.add(jPanel17, java.awt.BorderLayout.SOUTH);

        jPanel1.add(jPanel7);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(" Order  "));
        jPanel5.setRequestFocusEnabled(false);
        jPanel5.setLayout(new java.awt.BorderLayout());

        jScrollPane3.setViewportView(orderList);

        jPanel5.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        jPanel16.setPreferredSize(new java.awt.Dimension(178, 32));
        jPanel16.setLayout(new java.awt.BorderLayout());

        jLabel2.setPreferredSize(new java.awt.Dimension(30, 20));
        jPanel16.add(jLabel2, java.awt.BorderLayout.WEST);

        jButton7.setText("Start");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel16.add(jButton7, java.awt.BorderLayout.CENTER);

        jLabel3.setPreferredSize(new java.awt.Dimension(30, 20));
        jPanel16.add(jLabel3, java.awt.BorderLayout.EAST);

        jPanel5.add(jPanel16, java.awt.BorderLayout.SOUTH);

        jPanel1.add(jPanel5);
        jPanel5.getAccessibleContext().setAccessibleName(" Ordem");
        jPanel5.getAccessibleContext().setAccessibleDescription("Ordem");

        jPanel6.setLayout(new java.awt.BorderLayout());

        jPanel10.setPreferredSize(new java.awt.Dimension(20, 187));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 366, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel10, java.awt.BorderLayout.WEST);

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(" Produced  "));
        jPanel11.setLayout(new java.awt.BorderLayout());

        jScrollPane4.setViewportView(producedList);

        jPanel11.add(jScrollPane4, java.awt.BorderLayout.CENTER);

        jPanel15.setBorder(javax.swing.BorderFactory.createTitledBorder(" Failure  "));

        jScrollPane1.setViewportView(failureList);

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 148, Short.MAX_VALUE)
            .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 152, Short.MAX_VALUE)
            .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE))
        );

        jPanel11.add(jPanel15, java.awt.BorderLayout.PAGE_END);

        jPanel6.add(jPanel11, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel6);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(" Log  "));
        jPanel2.setPreferredSize(new java.awt.Dimension(792, 150));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane6.setViewportView(jTextArea1);

        jPanel2.add(jScrollPane6, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        jMenu1.setText("File");

        jMenuItem3.setText("Exit");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");

        jMenuItem4.setText("About...");
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        doExit();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void doExit() {
        GuiEvent ev = new GuiEvent(this, OrderAgent.EXITAGENT);
        oa.postGuiEvent(ev);
        try {
            Thread.sleep(1000);
        } catch (InterruptedException ex) {
        }
        dispose();
        System.exit(0);
    }

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        ((DefaultListModel) orderList.getModel()).clear();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int index = orderList.getSelectedIndex();
        if (index != -1) {
            DefaultListModel model = (DefaultListModel) orderList.getModel();
            model.remove(index);
        }
        orderList.updateUI();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int index = anagramList.getSelectedIndex();
        if (index != -1) {
            int size = (int) jSpinner1.getValue();
            String item = (String) anagramList.getSelectedValue();
            DefaultListModel model = (DefaultListModel) orderList.getModel();
            for (int i = 0; i < size; i++) {
                model.addElement(item);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        GuiEvent ev = new GuiEvent(this, OrderAgent.REFRESHSKILLS);
        oa.postGuiEvent(ev);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        DefaultListModel model = (DefaultListModel) orderList.getModel();
        String anagramas[] = new String[model.size()];
        for (int i = 0; i < model.size(); i++) {
            anagramas[i] = (String) model.get(i);
        }
        GuiEvent ev = new GuiEvent(this, OrderAgent.STARTORDERPRODUCE);
        ev.addParameter(anagramas);
        oa.postGuiEvent(ev);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        DefaultListModel model;
        String[] letras = AvailablesTxt.getText().split(" ");
        String anagram = GetAnagramDlg.getAnagramDlg(this, letras);
        if (anagram != "") {
            model = (DefaultListModel) anagramList.getModel();
            if (model.indexOf(anagram) == -1) {
                model.addElement(anagram);
            }
            anagramList.updateUI();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int index = anagramList.getSelectedIndex();
        if (index != -1) {
            DefaultListModel model = (DefaultListModel) anagramList.getModel();
            model.remove(index);
        }
        anagramList.updateUI();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        doExit();
    }//GEN-LAST:event_formWindowClosing

    private void AvailablesTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AvailablesTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AvailablesTxtActionPerformed

    public void refreshSkillsDone(String[] letras) {
        StringBuilder sb = new StringBuilder();
        for (String letra : letras) {
            sb.append(letra).append(" ");
        }
        AvailablesTxt.setText(sb.toString());
    }

    public void anagramDone(String anagrama, boolean failure) {
        DefaultListModel model;
        javax.swing.JList list;

        model = (DefaultListModel) (orderList.getModel());
        model.remove(0);
        orderList.updateUI();

        if (failure) {
            list = failureList;
        } else {
            list = producedList;
        }

        model = (DefaultListModel) (list.getModel());
        model.addElement(anagrama);
        list.updateUI();
    }

    public void removeListOrder() {
        int index = orderList.getSelectedIndex();
        if (index != 0) {
            DefaultListModel model = (DefaultListModel) orderList.getModel();
            model.remove(index);
        }
        orderList.updateUI();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
//        Debug.debugLevel = Debug.DEBUG;
//
//        try {
//
//            ContainerController cc;
//            AgentController ac;
//            jade.core.Runtime rt = jade.core.Runtime.instance();
//        
//            YPA ypa = new YPA();
//            cc = rt.createAgentContainer(new ProfileImpl(false));
//            ac = cc.acceptNewAgent(YPA.YPA_AGENT_NAME, ypa);
//            ac.start();
//
//            String letter;
//            int mod;
//            Stamper carimbo;
//
//            letter = "A";
//            mod = 1;
//            carimbo = new Stamper(letter, mod);
//            cc = rt.createAgentContainer(new ProfileImpl(false));
//            ac = cc.acceptNewAgent(letter, carimbo);
//            ac.start();
//
//            letter = "F";
//            mod = 2;
//            carimbo = new Stamper(letter, mod);
//            cc = rt.createAgentContainer(new ProfileImpl(false));
//            ac = cc.acceptNewAgent(letter, carimbo);
//            ac.start();
//            
//            letter = "M";
//            mod = 3;
//            carimbo = new Stamper(letter, mod);
//            cc = rt.createAgentContainer(new ProfileImpl(false));
//            ac = cc.acceptNewAgent(letter, carimbo);
//            ac.start();
//
//            
//            letter = "T";
//            mod = 4;
//            carimbo = new Stamper(letter, mod);
//            cc = rt.createAgentContainer(new ProfileImpl(false));
//            ac = cc.acceptNewAgent(letter, carimbo);
//            ac.start();
//            
//            letter = "U";
//            mod = 5;
//            carimbo = new Stamper(letter, mod);
//            cc = rt.createAgentContainer(new ProfileImpl(false));
//            ac = cc.acceptNewAgent(letter, carimbo);
//            ac.start();
//
//                 
//            Conveyor transp = new Conveyor();
//            cc = rt.createAgentContainer(new ProfileImpl(false));
//            ac = cc.acceptNewAgent("Conveyor", transp);
//            ac.start();
//        
//        } catch (StaleProxyException ex) {
//        
//            System.out.println("Error creating YPA. Exception: " + ex);
//            System.exit(-1);
//            return;
//        }
//        
        final String host;
        if (args.length == 1) {
            host = args[0];
        } else {
            host = "10.0.0.100";
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderGui(host).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AvailablesTxt;
    private javax.swing.JList anagramList;
    private javax.swing.JList failureList;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JList orderList;
    private javax.swing.JList producedList;
    // End of variables declaration//GEN-END:variables

}
